apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    component: client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: drawhub/client:latest
          imagePullPolicy: 'Never'
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 80
