name: CI

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
  build-base-image:
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # don't build the base image if no dependencies have changed
      - name: Check if package*.json files were modified
        id: check-deps
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            - package.json
            - package-lock.json

      - name: Log in to the Container registry
        if: steps.check-deps.outputs.any_changed == 'true'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker image
        if: steps.check-deps.outputs.any_changed == 'true'
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/utscc09/drawhub/base

      - name: Build and push Docker image
        if: steps.check-deps.outputs.any_changed == 'true'
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/utscc09/drawhub/base:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-client-image:
    runs-on: ubuntu-latest
    needs: build-base-image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/utscc09/drawhub/client

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./apps/client/Dockerfile
          push: true
          tags: ghcr.io/utscc09/drawhub/client:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-server-image:
    runs-on: ubuntu-latest
    needs: build-base-image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/utscc09/drawhub/server

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./apps/server/Dockerfile
          push: true
          tags: ghcr.io/utscc09/drawhub/server:latest
          labels: ${{ steps.meta.outputs.labels }}
